---
- hosts: localhost
  connection: local
  tasks:
    - name: set roles
      set_fact:
        is_archlinux: "{{ ansible_facts['os_family'] == 'Archlinux' }}"
        is_darwin: "{{ ansible_facts['os_family'] == 'Darwin' }}"
        roles: "{{ role_name | default(default_roles) }}"
      tags:
        - always

    - name: Roles to execute
      debug:
        var: roles
      tags:
        - always

    - name: Run roles
      include_role:
        apply:
          tags:
            - "{{ roles_item }}"
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items: "{{ roles }}"
      tags:
        - always
