#!/usr/bin/env sh

OS=$(uname)

if [ "$OS" = "Linux" ]; then
	PACMAN_PACKAGES=roles/packages/files/pacman_packages
	YAY_PACKAGES=roles/packages/files/yay_packages

	echo "Updating installed pacman package list..."
	pacman -Qqen > "$PACMAN_PACKAGES"
	echo "Updating installed AUR package list..."
	pacman -Qqem > "$YAY_PACKAGES"

	git add $PACMAN_PACKAGES
	git add $YAY_PACKAGES
fi

if [ "$OS" = "Darwin" ]; then
	BREW_PACKAGES=roles/packages/files/Brewfile

	echo "Updating installed brew packages..."
	brew bundle dump -f
	mv Brewfile $BREW_PACKAGES

	git add $BREW_PACKAGES
fi
