#!/usr/bin/env sh

PACMAN_PACKAGES=roles/packages/files/pacman_packages
YAY_PACKAGES=roles/packages/files/yay_packages

echo "Updating installed pacman package list..."
pacman -Qqent > "$PACMAN_PACKAGES"
echo "Updating installed AUR package list..."
pacman -Qqemt > "$YAY_PACKAGES"

git add $PACMAN_PACKAGES
git add $YAY_PACKAGES
