#!/usr/bin/env bash

sxhkd &
mopidy &
$HOME/.config/polybar/launch.sh &
feh --randomize --bg-fill $HOME/Pictures/Wallpapers/* &
compton -f -I 0.1 -O 0.07 &
pidof redshift || redshift -c $HOME/.config/redshift/redshift.conf &
killall -9 dunst && dunst &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 6
bspc config window_gap 20

bspc config normal_border_color $(xrdb -query | grep "*.background" | cut -f 2)
bspc config focused_border_color $(xrdb -query | grep "*.color5" | cut -f 2)
bspc config presel_border_color $(xrdb -query | grep "*.color6" | cut -f 2)

bspc config split_ratio 0.5

bspc config focus_follows_pointer true
bspc config click_to_focus true
