#!/usr/bin/env bash

sxhkd &
pulseaudio -D &
mopidy &
$HOME/.config/polybar/launch.sh &
feh --bg-scale $HOME/wallpaper.jpg &
compton -f -I 0.1 -O 0.07 &
pidof redshift || redshift -c $HOME/.config/redshift/redshift.conf &
killall -9 dunst && dunst &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 4
bspc config window_gap 10

bspc config normal_border_color "#282A36"
bspc config focused_border_color "#FF79C6"
bspc config presel_border_color "#44475A"

bspc config split_ratio 0.5

bspc config focus_follows_pointer true
bspc config click_to_focus true
