#!/usr/bin/env bash

bspc config border_width 2
bspc config window_gap 8

bspc config normal_border_color "#44475a"
bspc config active_border_color "#6272a4"
bspc config focused_border_color "#8be9fd"
bspc config presel_feedback_color "#6272a4"

bspc config split_ratio 0.5
bspc config top_padding 0

bspc config focus_follows_pointer true
bspc config click_to_focus true

bspc rule -a Spotify desktop=^9
bspc rule -a KeePassXC desktop=^10
bspc rule -a Zathura state=tiled

#===========================================
sxhkd &
nm-applet &
blueman-applet &
blueman-manager &
wg-systray &
killall -9 picom && picom -b
"$HOME"/.config/polybar/launch.sh &
pidof redshift || redshift -c "$HOME/.config/redshift/redshift.conf" &
killall -9 dunst && dunst &
bspc monitor -d I II III IV V VI VII VIII IX X
keepassxc &
spotify &

wmname LG3D
