#!/usr/bin/env bash

if ! PACMAN_UPDATES=$(checkupdates 2>/dev/null | wc -l); then
	PACMAN_UPDATES=0
fi

if ! AUR_UPDATES=$(yay -Qum 2>/dev/null | wc -l); then
	AUR_UPDATES=0
fi

ALL_UPDATES=$(("$PACMAN_UPDATES" + "$AUR_UPDATES"))

if [[ "ALL_UPDATES" -gt 0 ]]; then
	echo "$PACMAN_UPDATES 👻 $AUR_UPDATES ⬇"
else
	echo ""
fi
