#!/usr/bin/env sh

ACTIONS="⏯️ Toggle Play/Pause
⏭️ Next Track
⏮️ Previous Track
🔀 Toggle Shuffle"

SELECTED_ACTION=$(echo "$ACTIONS" | rofi -dmenu -i -p "Spotify Control: ")

if [ -z "$SELECTED_ACTION" ]; then
	exit 0
fi

case "$SELECTED_ACTION" in
	"⏯️ Toggle Play/Pause")
		spotify_player playback play-pause
		;;
	"⏭️ Next Track")
		spotify_player playback next
		;;
	"⏮️ Previous Track")
		spotify_player playback previous
		;;
	"🔀 Toggle Shuffle")
		spotify_player playback shuffle
		;;
esac
