#!/usr/bin/env bash

PANE_ACTIVE=$(tmux display-message -p '#{?pane_active,1,0}')
WINDOW_ZOOMED_FLAG=$(tmux display-message -p '#{?window_zoomed_flag,1,0}')

if [[ "$WINDOW_ZOOMED_FLAG" -eq 1 && "$PANE_ACTIVE" -eq 1 ]] ; then
  tmux select-pane -t 0 \; resize-pane -Z
	tmux select-pane -l
else
  tmux select-pane -t 0 \; resize-pane -Z
fi
