#!/usr/bin/env bash

bspc config active_border_color "#6272a4"
bspc config border_width 1
bspc config click_to_focus true
bspc config ignore_ewmh_focus true
bspc config focus_follows_pointer true
bspc config focused_border_color "#8be9fd"
bspc config normal_border_color "#44475a"
bspc config presel_feedback_color "#6272a4"
bspc config split_ratio 0.5
bspc config top_padding 0
bspc config window_gap 4
bspc monitor -d 1 2 3 4 5

bspc rule -a \* rectangle 1600x900+0+0 center=true
bspc rule -a Zathura state=tiled

bspc rule -a Spotify desktop=5 follow=off -o

blueman-applet &
launch_polybar &
nm-applet &
pgrep -x dunst || dunst &
pgrep -x sxhkd || sxhkd &
picom -b --fade-in-step=1 --fade-out-step=1 --fade-delta=0
spotify_player -d

wmname LG3D
