#!/usr/bin/env bash

bspc config active_border_color "#6272a4"
bspc config border_width 1
bspc config click_to_focus true
bspc config focus_follows_pointer true
bspc config focused_border_color "#8be9fd"
bspc config normal_border_color "#44475a"
bspc config presel_feedback_color "#6272a4"
bspc config split_ratio 0.5
bspc config top_padding 0
bspc config window_gap 4
bspc monitor -d I II III IV V VI VII VIII IX X

blueman-applet &
blueman-manager &
launch_polybar &
nm-applet &
pgrep -x dunst || dunst &
pgrep -x picom || picom -b
pgrep -x redshift || redshift &
pgrep -x sxhkd || sxhkd &

wmname LG3D
