#!/bin/bash

status=$(playerctl status 2>/dev/null)
max_output_len=50

if [ $? -eq 0 ]; then
    artist=$(playerctl metadata artist 2>/dev/null)
    title=$(playerctl metadata title 2>/dev/null)
    
    if [ -n "$artist" ] && [ -n "$title" ]; then
        if [ "$status" = "Playing" ]; then
            color="%{F#f8f8f2}"
        else
            color="%{F#6272a4}"
        fi
        
        text="${title} - ${artist}"
        if [ ${#text} -gt $max_output_len ]; then
            text="${text:0:$(($max_output_len-3))}..."
        fi
        echo "${color}${text}%{F-}"
    fi
fi
