#!/usr/bin/env sh

echo "Updating installed pacman package list..."
pacman -Qqen > pacman_packages
echo "Updating installed AUR package list..."
pacman -Qqem > yay_packages
echo "Updating installed vscode extension list"
code --list-extensions > vscode/extensions

git commit -am "chore: update lists of packages/extensions installed" --no-verify > /dev/null

echo "Done!"
