#!/bin/sh

echo "Updating installed pacman package list..."
pacman -Qnq > pacman_packages
echo "Updating installed AUR package list..."
pacman -Qmq > yay_packages
echo "Updating installed vscode extension list"
code --list-extensions > vscode/extensions

git commit -am "Update lists of packages/extensions installed" --no-verify > /dev/null

echo "Done!"
