#!/usr/bin/env zsh

setopt AUTO_CD
setopt AUTO_PARAM_SLASH
setopt AUTO_PUSHD
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_DUPS
setopt HIST_VERIFY
setopt INC_APPEND_HISTORY
setopt LIST_PACKED
setopt MENU_COMPLETE
setopt NO_FLOW_CONTROL
setopt NO_HIST_IGNORE_ALL_DUPS
setopt NO_HIST_IGNORE_SPACE
setopt SHARE_HISTORY
